# Generated by Django 3.1.6 on 2021-06-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_id',
            field=models.CharField(default='email_obsolete@obs.com', max_length=200),
        ),
    ]
