# Generated by Django 3.1.6 on 2021-06-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_services_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(max_length=10),
        ),
    ]
