# Generated by Django 3.1.6 on 2021-06-02 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_userprofile_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_id',
        ),
    ]
