# Generated by Django 3.1.6 on 2021-06-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_remove_userprofile_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviders',
            name='provider_image_name',
        ),
        migrations.AddField(
            model_name='serviceproviders',
            name='provider_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
