# Generated by Django 3.1.6 on 2021-06-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_auto_20210603_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviders',
            name='provider_image',
        ),
        migrations.AddField(
            model_name='serviceproviders',
            name='provider_image_name',
            field=models.CharField(default='default.jpg', max_length=100),
        ),
    ]
